charts:
  default: highcharts

  highcharts:
    include:
      - jquery.min.js
      - highcharts.min.js
      - global.js
    convert:
      file: highcharts-convert.js
      command: phantomjs %s -infile %s -outfile %s -scale 2.5

  googlecharts:
    defaults:
      width: 100%
      height: 600px
    include:
      - https://www.gstatic.com/charts/loader.js
      - global.js
    convert:
      file: googlecharts-convert.js
      command: phantomjs --ignore-ssl-errors=true %s %s %s